version: '3.8'
services:
    php-apache:
        container_name: vsnippet-codeinjection-file-write-38
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 1337:80
